version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8  
    commands:
      - echo Entering install phase...   
  pre_build:
    commands:
      - echo Entering pre_build phase...
      - echo Nothing to do in the pre_build phase...          
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`      
      - mvn -f pom.xml test
      - mvn -f pom.xml package      
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
reports:
  SurefireReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: 'target/surefire-reports' # Location of the reports 