version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    runtime-versions:
      java: corretto8 

  pre_build:
    commands:
      - echo Entering pre_build phase...
      - echo Nothing to do in the pre_build phase...      
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`    
      - mvn surefire-report:report 
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
reports:
  SurefireReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/cucumber.json'
    base-directory: 'target/surefire-reports' # Location of the reports 