version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    runtime-versions:
       java: openjdk8
    commands:
        - apt-get update -y
        - apt-get install -y maven
  pre_build:
    commands:
       - java -version
       - mvn -version      
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`    
      - mvn surefire-report:report 
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
reports:
  SurefireReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/cucumber.json'
    base-directory: 'target/surefire-reports' # Location of the reports 